9. flask进阶&博客系统  av67620140/7/blog/app/models/__init__.py
from .user import User

9. flask进阶&博客系统  av67620140/7/blog/app/models/user.py
from flask import current_app
from app.extensions import db, login_manager
# 生成token使用
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
# 密码散列及校验
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
    # 指定表名
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(32), unique=True)
    password_hash = db.Column(db.String(128))
    email = db.Column(db.String(64), unique=True)
    confirmed = db.Column(db.Boolean, default=False)

    # 保护字段
    @property
    def password(self):
        raise AttributeError('密码是不可读属性')

    # 设置密码，加密存储
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 密码校验
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    # 生成用户激活的token
    def generate_activate_token(self, expires_in=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expires_in=expires_in)
        return s.dumps({'id': self.id})

    # 激活账户时的token校验，校验时还不知道用户信息，需要静态方法
    @staticmethod
    def check_activate_token(token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token)
        except:
            return False
        user = User.query.get(data.get('id'))
        if user is None:
            # 不存在此用户
            return False
        if not user.confirmed:
            # 账户没有激活时才激活
            user.confirmed = True
            db.session.add(user)
        return True


@login_manager.user_loader
def loader_user(user_id):
    return User.query.get(int(user_id))

9. flask进阶&博客系统  av67620140/7/blog/app/forms/__init__.py
from .user import RegisterForm, LoginForm, PasswordForm

9. flask进阶&博客系统  av67620140/7/blog/app/forms/user.py
# 导入表单基类
from flask_wtf import FlaskForm
# 导入相关字段
from wtforms import StringField, PasswordField, SubmitField, BooleanField, ValidationError
# 导入验证器类
from wtforms.validators import DataRequired, EqualTo, Email, Length
from app.models import User


# 用户注册表单
class RegisterForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), Length(6, 18, message='用户名必须在6~18个字符之间')])
    password = PasswordField('密码', validators=[DataRequired(), Length(6, 18, message='密码长度必须在6~18个字符之间')])
    confirm = PasswordField('确认密码', validators=[EqualTo('password', message='两次密码不一致')])
    email = StringField('邮箱', validators=[Email(message='邮箱格式不正确')])
    submit = SubmitField('立即注册')

    # 自定义验证器，验证用户名
    def validate_username(self, field):
        if User.query.filter_by(username=field.data).first():
            raise ValidationError('该用户名已存在，请选用其它用户名')

    # 自定义验证器，验证邮箱
    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('该邮箱已使用，请选用其它邮箱')


# 用户登录表单
class LoginForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired()])
    password = PasswordField('密码', validators=[DataRequired()])
    remember_me = BooleanField('记住我')
    submit = SubmitField('立即登录')


# 修改密码表单
class PasswordForm(FlaskForm):
    old_pwd = PasswordField('原密码', validators=[DataRequired()])
    new_pwd = PasswordField('新密码', validators=[DataRequired(), Length(6, 18, message='密码长度必须在6~18个字符之间')])
    confirm = PasswordField('确认密码', validators=[EqualTo('new_pwd', message='两次密码不一致')])
    submit = SubmitField('确认修改')

9. flask进阶&博客系统  av67620140/7/blog/app/__init__.py
from flask import Flask, render_template
from app.config import config
from app.extensions import config_extensions
from app.views import config_blueprint


def create_app(config_name):
    # 创建应用实例
    app = Flask(__name__)
    # 通过类初始化配置
    app.config.from_object(config[config_name])
    # 调用初始化函数
    config[config_name].init_app(app)
    # 配置相关扩展
    config_extensions(app)
    # 配置相关蓝本
    config_blueprint(app)
    # 配置错误显示
    config_errorhandler(app)
    # 返回应用实例
    return app


def config_errorhandler(app):
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('errors/404.html')

9. flask进阶&博客系统  av67620140/7/blog/app/views/__init__.py
from .main import main
from .user import user


# 蓝本配置元组
DEFAULT_BLUEPRINT = (
    # 蓝本 前缀
    (main, ''),
    (user, '/user')
)


# 注册蓝本
def config_blueprint(app):
    for blue_print,url_prefix in DEFAULT_BLUEPRINT:
        app.register_blueprint(blue_print, url_prefix=url_prefix)

9. flask进阶&博客系统  av67620140/7/blog/app/views/main.py
from flask import Blueprint, render_template, current_app
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer


main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('main/index.html')


@main.route('/jiami/')
def jiami():
    return generate_password_hash('123456')


@main.route('/check/<password>')
def check(password):
    # 密码校验函数：加密后的值  密码
    # 正确：True，错误：False
    if check_password_hash('pbkdf2:sha256:50000$8tHnM54f$c1518c6e491e0a7c5ebd90beb8b56c1d3b03cef66ad940c566578e6a5cfd62ea', password):
        return '密码正确'
    else:
        return '密码错误'


@main.route('/generate_token/')
def generate_token():
    s = Serializer(current_app.config['SECRET_KEY'], expires_in=3600)
    # 加密指定的数据，已字典的形式传入
    return s.dumps({'id': 250})


@main.route('/activate/<token>')
def activate(token):
    s = Serializer(current_app.config['SECRET_KEY'])
    try:
        data = s.loads(token)
    except:
        return 'token有误'
    return str(data.get('id'))

9. flask进阶&博客系统  av67620140/7/blog/app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, request
from app.forms import RegisterForm, LoginForm, PasswordForm
from app.email import send_mail
from app.models import User
from app.extensions import db
from flask_login import login_user, logout_user, login_required, current_user


user = Blueprint('user', __name__)


@user.route('/register/', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # 创建对象
        u = User(username=form.username.data, password=form.password.data, email=form.email.data)
        # 写入数据库
        db.session.add(u)
        # 因为下面产生token时需要用到用户id，此时还没有用户id
        db.session.commit()
        # 生成token
        token = u.generate_activate_token()
        # 发送激活邮件
        send_mail(form.email.data, '账户激活', 'email/account_activate', token=token, username=form.username.data)
        flash('激活邮件已发送，请点击链接完成用户激活')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


@user.route('/activate/<token>')
def activate(token):
    if User.check_activate_token(token):
        flash('账户激活成功')
        return redirect(url_for('user.login'))
    else:
        flash('账户激活失败')
        return redirect(url_for('main.index'))


@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        if u is None:
            flash('无效的用户名')
        elif u.verify_password(form.password.data):
            # 验证通过，用户登录，顺便可以完成'记住我'的功能
            login_user(u, remember=form.remember_me.data)
            # 如果有下一跳转地址就跳转到指定地址，没有跳转到首页
            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash('无效的密码')
    return render_template('user/login.html', form=form)


@user.route('/logout/')
# 保护路由
@login_required
def logout():
    logout_user()
    flash('您已退出登录')
    return redirect(url_for('main.index'))


@user.route('/profile/')
@login_required
def profile():
    return render_template('user/profile.html')


@user.route('/change_password/', methods=['GET', 'POST'])
@login_required
def change_password():
    form = PasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_pwd.data):
            current_user.password = form.new_pwd.data
            db.session.add(current_user)
            flash('密码修改成功，下次请使用新密码登录')
            return redirect(url_for('main.index'))
        else:
            flash('无效的原始密码')
            return redirect(url_for('user.change_password'))
    return render_template('user/change_password.html', form=form)

9. flask进阶&博客系统  av67620140/7/blog/app/templates/common/base.html
{% extends 'bootstrap/base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block title %}博客{% endblock %}

{% block navbar %}
<nav class="navbar navbar-inverse" style="border-radius: 0px;">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target=".navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">博客</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="#">板块一</a></li>
                <li><a href="#">板块二</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
                <li><a href="{{url_for('user.logout')}}">退出</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{current_user.username}}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('user.profile')}}">个人信息</a></li>
                        <li><a href="{{url_for('user.change_password')}}">修改密码</a></li>
                        <li><a href="#">修改邮箱</a></li>
                        <li><a href="#">修改头像</a></li>
                    </ul>
                </li>
            {% else %}
                <li><a href="{{url_for('user.login')}}">登录</a></li>
                <li><a href="{{url_for('user.register')}}">注册</a></li>
            {% endif %}
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
</nav>
{% endblock %}

{% block content %}
<div class="container">
    {# get_flashed_messages获取所有的flash消息 #}
    {% for message in get_flashed_messages() %}
        <div class="alert alert-warning alert-dismissible"
             role="alert">
            <button type="button" class="close"
                    data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
    {% endfor %}
    {% block page_content %}默认内容{% endblock %}
</div>
{% endblock %}

9. flask进阶&博客系统  av67620140/7/blog/app/templates/main/index.html
{% extends 'common/base.html' %}

{% block title %}首页{% endblock %}

{% block page_content %}
    这里是最新的博客内容
{% endblock %}

9. flask进阶&博客系统  av67620140/7/blog/app/templates/user/change_password.html
{% extends 'common/base.html' %}

{% block title %}修改密码{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

9. flask进阶&博客系统  av67620140/7/blog/app/templates/user/login.html
{% extends 'common/base.html' %}

{% block title %}用户登录{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}

9. flask进阶&博客系统  av67620140/7/blog/app/templates/user/profile.html
{% extends 'common/base.html' %}

{% block title %}个人信息{% endblock %}

{% block page_content %}
<div class="form-group">
    <label for="InputUsername">用户名</label>
    <input type="text" class="form-control" id="InputUsername" value="{{current_user.username}}" disabled>
</div>
<div class="form-group">
    <label for="InputEmail">邮箱</label>
    <input type="text" class="form-control" id="InputEmail" value="{{current_user.email}}" disabled>
</div>
{% endblock %}

9. flask进阶&博客系统  av67620140/7/blog/app/templates/user/register.html
{% extends 'common/base.html' %}

{% block title %}欢迎注册{% endblock %}

{% block page_content %}
    {{ wtf.quick_form(form) }}
{% endblock %}